# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visittomm_en', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='flights',
            new_name='d_airport',
        ),
        migrations.AddField(
            model_name='cities',
            name='i_airport',
            field=models.BooleanField(default=False),
        ),
    ]
