# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visittomm_en', '0003_regionsstates_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='lon',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
