# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visittomm_en', '0005_auto_20160421_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='regionsstates',
            old_name='title',
            new_name='name',
        ),
    ]
