# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visittomm_en', '0006_auto_20160421_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='title',
            new_name='name',
        ),
    ]
