# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visittomm_en', '0007_auto_20160421_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='user_ids',
            field=models.ManyToManyField(related_name='user_ids', to=settings.AUTH_USER_MODEL),
        ),
    ]
