# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 16:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visittomm_en', '0008_auto_20160421_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('lat', models.CharField(max_length=20, null=True)),
                ('lon', models.CharField(max_length=20, null=True)),
                ('i_airport', models.BooleanField(default=False)),
                ('d_airport', models.BooleanField(default=False)),
                ('bus', models.BooleanField(default=False)),
                ('cruise', models.BooleanField(default=False)),
                ('car', models.BooleanField(default=False)),
                ('city', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_city_id', to='visittomm_en.Cities')),
                ('region_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_region_id', to='visittomm_en.RegionsStates')),
            ],
        ),
        migrations.AlterField(
            model_name='packages',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_destination_city_id', to='visittomm_en.Cities'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_origin_city_id', to='visittomm_en.Cities'),
        ),
    ]
