# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visittomm_en', '0009_auto_20160421_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='train',
            field=models.BooleanField(default=False),
        ),
    ]
