# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visittomm_en', '0010_destinations_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='language_spoken',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='sights_stops',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='time_length',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='transport_includes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_destination_city_id', to='visittomm_en.Cities'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_origin_city_id', to='visittomm_en.Cities'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='rank',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
